# -*- coding: utf-8 -*-
"""Football Standings

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wV6JP-oE7pvVs8--TCa3THAns2xvOcHq

The API that was utilized for this assignment showed all Soccer standings for the designated league you are looking for based on espn website.
"""

import requests
import pandas as pd

"""Get Request for basic summmary of all the different leagues andd there standings"""

jsonresponse = requests.get('https://api-football-standings.azharimm.site/leagues')

jsonresponse.status_code

jsonresponse.json()

"""Get request for League Standtings in the English Primeier League"""

Jsonresponse2 = requests.get('https://api-football-standings.azharimm.site/leagues/eng.1/standings?season=2020&sort=asc')

Jsonresponse2.status_code

Jsonresponse2.json()